name: flutter_active_loaders
description: package to show loaders you can use it to show some awesome loaders on user screen.
version: 7.2.0
homepage: https://github.com/mazab99/loaders

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  collection: ^1.17.2

dev_dependencies:
  recase: ^4.1.0
  args: ^2.4.1
  flutter_test:
    sdk: flutter
  version: ^2.0.0
  ansicolor: ^2.0.1
  flutter_lints: ^2.0.1
  pub_semver: ^2.1.4

flutter:
  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: lib/src/asowomeIcons/fonts/fa-brands-400.ttf
          weight: 400
    - family: FontAwesomeRegular
      fonts:
        - asset: lib/src/asowomeIcons/fonts/fa-regular-400.ttf
          weight: 400
    - family: FontAwesomeSolid
      fonts:
        - asset: lib/src/asowomeIcons/fonts/fa-solid-900.ttf
          weight: 900



          # dart pub publish --dry-run
          # dart pub publish