name: loaders
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/mazab99/loaders

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
