name: flutter_active_loaders
description: package to show loaders.
version: 7.1.0
homepage: https://github.com/mazab99/loaders

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2
  collection: ^1.16.0

dev_dependencies:
  recase: ^4.0.0
  args: ^2.3.0
  flutter_test:
    sdk: flutter
  version: ^2.0.0
  ansicolor: ^2.0.1
  flutter_lints: ^1.0.0
  pub_semver: ^2.1.1

flutter:
  fonts:
    - family: FontAwesomeBrands
      fonts:
        - asset: lib/src/asowomeIcons/fonts/fa-brands-400.ttf
          weight: 400
    - family: FontAwesomeRegular
      fonts:
        - asset: lib/src/asowomeIcons/fonts/fa-regular-400.ttf
          weight: 400
    - family: FontAwesomeSolid
      fonts:
        - asset: lib/src/asowomeIcons/fonts/fa-solid-900.ttf
          weight: 900



          # dart pub publish --dry-run
          # dart pub publish