name: flutter_active_loaders
description: package to show loaders.
version: 2.0.0
homepage: https://github.com/mazab99/loaders

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.2
  collection: ^1.16.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
